sudo: false

language: node_js

notifications:
  email: false

script: "npm run $TASK"

matrix:
  include:
  - node_js: '0.12'
    env: TASK=test
    before_install: npm -g i npm@2

  - node_js: 'iojs'
    env: TASK=test
    before_install: npm -g i npm@2

  - node_js: '4'
    env: TASK=test
    before_install: npm -g i npm@2

  - node_js: '4'
    env: TASK=test
    before_install: npm -g i npm@3

  - node_js: '5'
    env: TASK=test
    before_install: npm -g i npm@3
